/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/_monika/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report whether Redis and Postgres are actually reachable right now.
         */
        get: operations["health__monika_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_monika/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Incidents
         * @description Newest-first incident feed with keyset pagination on (created_at, id).
         */
        get: operations["list_incidents__monika_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_monika/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Incident
         * @description One incident with its signals, overrides and (async) LLM explanation.
         */
        get: operations["get_incident__monika_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_monika/sessions/{session_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Current ladder state and score, read from Redis (D-04).
         */
        get: operations["get_session__monika_sessions__session_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_monika/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description The SSE endpoint. The dashboard never polls; it consumes this stream.
         */
        get: operations["events__monika_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_monika/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats__monika_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_monika/endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Endpoints */
        get: operations["get_endpoints__monika_endpoints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_monika/incidents/{incident_id}/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Override Incident */
        post: operations["override_incident__monika_incidents__incident_id__override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_monika/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset
         * @description Dashboard Settings "Reset demo data". Fast (<1s): clears incidents/sessions/transient
         *     detector state but keeps learned baselines — for a full re-seed use `make reset` (CLI).
         */
        post: operations["reset__monika_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_monika/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Start one scenario as a background task; return immediately with a run id.
         *     Refuses to run two scenarios concurrently (409).
         */
        post: operations["simulate__monika_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_monika/simulate/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Simulate Status */
        get: operations["simulate_status__monika_simulate__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EndpointOut
         * @description One row of the §13.1 risk map: config + baseline snapshot + observed risk.
         *
         *     risk_level is derived from incidents seen on this endpoint (last 30 min):
         *     'red' if any incident scored >= 80, 'amber' if any incident exists (>= 30),
         *     else 'green'. Baseline columns are the D-03 display snapshot (Redis is authoritative).
         */
        EndpointOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Method */
            method: string;
            /** Path Pattern */
            path_pattern: string;
            /** Auth Required */
            auth_required: boolean;
            /** Admin Only */
            admin_only: boolean;
            /** Sensitive Fields */
            sensitive_fields: string[];
            /** Baseline Rpm Mean */
            baseline_rpm_mean: number;
            /** Baseline Rpm Std */
            baseline_rpm_std: number;
            /** Baseline Resp Bytes */
            baseline_resp_bytes: number;
            /** Incident Count */
            incident_count: number;
            /** Max Risk Score */
            max_risk_score: number | null;
            /** Risk Level */
            risk_level: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness plus real dependency connectivity.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Redis */
            redis: boolean;
            /** Postgres */
            postgres: boolean;
        };
        /** IncidentDetailOut */
        IncidentDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Session Key */
            session_key: string;
            /**
             * Endpoint Id
             * Format: uuid
             */
            endpoint_id: string;
            /** Threat Type */
            threat_type: string;
            /** Risk Score */
            risk_score: number;
            /** Confidence */
            confidence: number;
            /** Action Taken */
            action_taken: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Llm Explanation */
            llm_explanation: string | null;
            /** Llm Next Step */
            llm_next_step: string | null;
            /** Signals */
            signals: components["schemas"]["SignalOut"][];
            /** Overrides */
            overrides: components["schemas"]["OverrideOut"][];
        };
        /** IncidentListOut */
        IncidentListOut: {
            /** Items */
            items: components["schemas"]["IncidentOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** IncidentOut */
        IncidentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Session Key */
            session_key: string;
            /**
             * Endpoint Id
             * Format: uuid
             */
            endpoint_id: string;
            /** Threat Type */
            threat_type: string;
            /** Risk Score */
            risk_score: number;
            /** Confidence */
            confidence: number;
            /** Action Taken */
            action_taken: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OverrideOut */
        OverrideOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Analyst */
            analyst: string;
            /** Action */
            action: string;
            /** Reason */
            reason: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OverrideRequest */
        OverrideRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "acknowledge" | "unblock" | "false_positive" | "force_block";
            /** Reason */
            reason: string;
            /** Analyst */
            analyst: string;
        };
        /** ResetOut */
        ResetOut: {
            /** Incidents Cleared */
            incidents_cleared: number;
            /** Signals Cleared */
            signals_cleared: number;
            /** Preserved Incidents */
            preserved_incidents: number;
        };
        /** SessionStateOut */
        SessionStateOut: {
            /** Session Key */
            session_key: string;
            /** State */
            state: string;
            /** Score */
            score: number;
            /** Last Signal At */
            last_signal_at: number | null;
            /** Signals 5M */
            signals_5m: number;
        };
        /** SignalOut */
        SignalOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Category */
            category: string;
            /** Severity */
            severity: number;
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Request Id */
            request_id: string;
            /** Session Key */
            session_key: string;
            /** Endpoint Id */
            endpoint_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SimulateRequest */
        SimulateRequest: {
            /** Scenario */
            scenario: string;
        };
        /** SimulateRun */
        SimulateRun: {
            /** Run Id */
            run_id: string;
            /** Scenario */
            scenario: string;
            /** Status */
            status: string;
        };
        /** StatsOut */
        StatsOut: {
            /** Total Requests */
            total_requests: number;
            /** Incidents */
            incidents: number;
            /** Blocked */
            blocked: number;
            /** Endpoints Configured */
            endpoints_configured: number;
            /** Precision */
            precision: number | null;
            /** Recall */
            recall: number | null;
            /** Benign By Rung */
            benign_by_rung: {
                [key: string]: number;
            };
            /**
             * Window Minutes
             * @default 30
             */
            window_minutes: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health__monika_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_incidents__monika_incidents_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_incident__monika_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session__monika_sessions__session_key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events__monika_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stats__monika_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    get_endpoints__monika_endpoints_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndpointOut"][];
                };
            };
        };
    };
    override_incident__monika_incidents__incident_id__override_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset__monika_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetOut"];
                };
            };
        };
    };
    simulate__monika_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_status__monika_simulate__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
