"use client";

import { CheckCircle2, Play, Radio, RotateCcw } from "lucide-react";
import { useState } from "react";

const scenarios = [["idor", "BOLA enumeration", "Sequential object access against another user's records.", "D1 + D2 + D3 -> BOLA_ENUMERATION >= 90"], ["stuffing", "Credential stuffing", "Repeated login failures across distinct usernames.", "D3 -> CREDENTIAL_STUFFING >= 75"], ["sqli", "SQL injection", "Tautology payloads sent to the search endpoint.", "D4 -> INJECTION >= 60"], ["scrape", "Sensitive scrape", "High-volume product reads expose configured fields.", "D2 + D4 -> DATA_EXPOSURE >= 85"], ["admin", "Function abuse", "A non-admin token probes the admin surface.", "D1 -> FUNCTION_LEVEL_AUTH >= 70"], ["benign", "Benign burst", "Normal traffic control with no expected incident.", "No incident expected"]];

export default function SimulatorPage() {
	const [running, setRunning] = useState<string | null>(null);
	const [completed, setCompleted] = useState<string[]>([]);
	const run = (scenario: string) => { setRunning(scenario); window.setTimeout(() => { setRunning(null); setCompleted((current) => [...current, scenario]); }, 900); };
	return <div className="space-y-6"><header className="flex items-end justify-between"><div><p className="eyebrow">Traffic lab</p><h1 className="page-title">Simulator</h1></div><span className="mono text-xs text-zinc-600">FIXTURE RUNNER</span></header><div className="console-card border-indigo-400/20 bg-indigo-400/3 p-4"><div className="flex items-center gap-3"><Radio size={17} className="text-indigo-300" /><div><p className="text-sm text-zinc-200">Run a controlled scenario</p><p className="text-xs text-zinc-500">Fixture mode records the expected detection result without requiring the backend.</p></div></div></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{scenarios.map(([id, name, description, expected]) => { const isRunning = running === id; const isComplete = completed.includes(id); return <article key={id} className="console-card flex min-h-48 flex-col p-4"><div className="flex items-start justify-between gap-3"><h2 className="font-medium text-zinc-200">{name}</h2>{isComplete && <CheckCircle2 size={16} className="text-emerald-400" />}</div><p className="mt-2 text-xs leading-5 text-zinc-500">{description}</p><p className="mono mt-4 text-[11px] leading-4 text-zinc-600">Expected: {expected}</p><button type="button" onClick={() => run(id)} disabled={isRunning} className="mt-auto flex items-center justify-center gap-2 rounded-md border border-zinc-700 bg-zinc-800 px-3 py-2 text-xs text-zinc-300 hover:border-indigo-400/50 hover:text-indigo-300 disabled:opacity-50">{isRunning ? <RotateCcw size={14} className="animate-spin" /> : <Play size={14} />}{isRunning ? "Running" : isComplete ? "Run again" : "Run scenario"}</button></article>; })}</div></div>;
}
