"use client";

import { Check, RotateCcw, ShieldCheck } from "lucide-react";
import { useState } from "react";

export default function SettingsPage() {
	const [reset, setReset] = useState(false);
	return <div className="space-y-6"><header><p className="eyebrow">System configuration</p><h1 className="page-title">Settings</h1></header><div className="grid gap-3 lg:grid-cols-2"><section className="console-card p-5"><h2 className="text-sm font-medium text-zinc-200">Protection policy</h2><div className="mt-5 divide-y divide-zinc-800">{[["Observe", "score >= 30"], ["Rate limit", "score >= 45"], ["Challenge", "score >= 60"], ["Block", "score >= 75"], ["Revoke", "score >= 90"]].map(([name, value]) => <div key={name} className="flex items-center justify-between py-3 text-xs"><span className="text-zinc-400">{name}</span><span className="mono text-zinc-600">{value}</span></div>)}</div></section><section className="console-card p-5"><h2 className="text-sm font-medium text-zinc-200">Runtime status</h2><div className="mt-5 space-y-3">{[["Detection engine", "Protected", true], ["Baseline learning", "Collecting traffic", false], ["LLM explainer", "Enabled after decision", true], ["Fast mode", "Disabled", false]].map(([name, value, okay]) => <div key={name as string} className="flex items-center justify-between rounded-md bg-zinc-950/60 px-3 py-3 text-xs"><span className="text-zinc-400">{name as string}</span><span className="flex items-center gap-2 text-zinc-500">{okay ? <Check size={14} className="text-emerald-400" /> : <span className="size-1.5 rounded-full bg-amber-400" />}{value as string}</span></div>)}</div></section></div><section className="console-card flex items-center justify-between gap-4 p-5"><div className="flex items-center gap-3"><ShieldCheck size={18} className="text-indigo-300" /><div><h2 className="text-sm font-medium text-zinc-200">Demo data</h2><p className="mt-1 text-xs text-zinc-600">Reset incidents, sessions, and learning state before a rehearsal.</p></div></div><button type="button" onClick={() => setReset(!reset)} className="flex items-center gap-2 rounded-md border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-300 hover:bg-red-500/20"><RotateCcw size={14} />{reset ? "Reset queued" : "Reset demo data"}</button></section></div>;
}
